name: "Sample react ci pipeline/workflow"

on:
    push:
        branches:
            - main
            - test

    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Setup nodeJs
              uses: actions/setup-node@v4
              with:
                node-version: '20'
           
            - name: Check node version
              run: node --version

            - name: Clone the repository
              uses: actions/checkout@v2

            - name: "Install dependencies"
              run:  npm install

            - name: "List depositories"
              run:  ls

            - name: "Run test"
              run:  npm test
            
            - name: "Run build"
              run:   npm run build

              #41:48
           
